### ISSUE TITLE
navigation keys not working in Primephonic

### ISSUE THREAD

**Issue by BachoSeven** [Jelmerro/Vieb#281] opened 2021-08-24 20:11 UTC
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Navigation keys in normal mode are not working on https://play.primephonic.com website(classical music HQ streaming).

**To Reproduce**
I think it's enough to visit the site, an account is not needed to just navigate.

**Expected behavior**
Navigation keys(j/k) in normal mode(and/or arrow keys in insert mode, which also don't work) to be available

**Specs**
 - OS: Arch Linux
 - Version: 5.3.0

Edit: btw, this has been the case for some time, and I thought it was an issue just inside of the Erwic instance which I had created for the service but it is not, I also could reproduce it inside normal Vieb

**Comment by Jelmerro** [comment] 2021-08-24 20:19
The page isn't scrollable, just a section of it is. This means that page scrolling actions won't work, because you don't specify where to scroll using the pointer. Duplicate of many other issues including https://github.com/Jelmerro/Vieb/issues/150, see my comment there and the `:h scrolling` help for more.

**Comment by Jelmerro** [comment] 2021-08-24 20:19
Also, I'll be adding to the FAQ in a bit, as this is the third issue in a week mentioning this.

**Closed by Jelmerro** 2021-08-24 20:19 UTC
Labels: duplicate, question

**Comment by BachoSeven** [comment] 2021-08-24 22:09
Thanks for the explanation, I hadn't thought it was this common.

And the tip about mapping pointer actions works pretty well for sites like in my case where the scrolling section is quite large.

How not feasible would it be to make a system where the user could set to move the pointer to a certain relative position/html element for certain pages? This way one wouldn't have to manually move the pointer each time
