### ISSUE TITLE
`mousevisualmode` doesn't work with multi-click selections

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#257] opened 2021-06-26 17:19 UTC
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
With `mousevisualmode=activate`, visual mode is correctly entered when selections with the mouse are dragged.
However, when I double- or triple-click a bit of text to highlight it, visual mode is not entered.

**To Reproduce**
- Go to any site with text and double-click the text
- This highlights a "word" but doesn't enter visual mode

**Expected behavior**
Visual mode should also be activated, as if the selection were dragged instead of double-clicked.

**Specs**
 - OS: Windows 10
 - Version: Vieb 5.2.0

**Comment by Jelmerro** [comment] 2021-06-27 11:16
I couldn't get this to be detected, as you don't know where to select should be started or ended, you just know the selected text. So you either have to guess the start and end position or use a function that I wasn't able to find that does this.

**Comment by ottopiramuthu** [comment] 2021-06-27 11:25
If there's no way to detect this I'd be fine with it always being on one side or the other since it can be easily adjusted with `o`.

**Comment by Jelmerro** [comment] 2021-06-27 11:33
The problem is that you don't know either of the two locations, because the double-click can be done in the middle, so the current system to detect this for drag actions doesn't work. We need a different solution to make this work for double-click, but I haven't found one so far.

**Comment by Jelmerro** [comment] 2023-11-14 16:35
I recently found out that you can get the bounding box for a selection, and have used that to fix this problem here: https://github.com/Jelmerro/Vieb/commit/68cb029c90e472ea9a7ec7da792a9ed4b52b7f93. It will be included in the V11 release.

**Comment by Jelmerro** [comment] 2023-12-07 12:37
Fixed in 11.0.0 :tada:

**Closed by Jelmerro** 2023-12-07 12:37 UTC
Labels: bug, mode-visual
