### ISSUE TITLE
Integrate a real vi-like editor in text-areas

### ISSUE THREAD

**Issue by rambip** [Jelmerro/Vieb#272] opened 2021-08-17 14:37 UTC
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Problem**
I just discovered this project, and it seems amazing.

 Currently I'm using 2 browsers: 
- Qutebrowser to find informations quickly
- Brave for everything where qute is not sufficient.

It looks like vieb could do both, except for one thing: editing text inside the browser.

I use the [firenvim](https://github.com/glacambre/firenvim) neovim plugin to embed neovim inside my chromium-based browser. Each time I click on a text area, it is replaced by an instance of neovim.

**Request**

What I'm asking is a way to do that exact thing in vieb: editing text in text areas with a vi-like editor, or even port the "firenvim" project to vieb.

Vieb should handle both fast navigation (e.g wikipedia) and text editing (github posts).

There is a real desire for that, and I know no vim-inspired editor that is able to do that.

**caveats**
If it is possible, I'm not sure what the right behaviour would be for vieb.

I think a special mode like "editor mode" is required.

Imagine you are in insert mode in a text-area, and you want to switch tab: you have to hit escape to leave insert mode, then use a key binding (shift+escape ?) to leave editor-mode, and then use J to change tab.

**Comment by Jelmerro** [comment] 2021-08-17 16:16
This is a duplicate of #61, so I might reword the title of it to make it more clear what it means. Basically, this is a lot of work to built from scratch, I would say about as much work as making your own Vim, unless we would use a plugin/module to do so.

In the meantime, you can try either of these options:
- Install the extension with `:extension install` on the chrome/firefox extension/addon page and see if it works without a UI (I don't expect it to, but it might just work)
- Or just use the `<editWithVim>` action to edit the current input field in the external editor set by `vimcommand`, you can do `:help editWithVim` or `:h vimcommand` for more details and instructions

I'll close this ticket as a duplicate of #61, so please continue the discussion there. If the extension route doesn't work, refer to #130.

**Closed by Jelmerro** 2021-08-17 16:16 UTC
Labels: duplicate, enhancement, mode-insert

**Comment by rambip** [comment] 2021-08-18 11:27
I didn't test the extension yet, but it can't work well: if I am in insert mode in a text area and I hit escape, vieb will catch it and I will not be able to type any more.
Is there a trick to disable the escape ?

**Comment by Jelmerro** [comment] 2021-08-18 17:27
You can do `:iunmap! <Esc>` to do so, note the `!` after map, which is Vieb specific syntax to also overwrite the default mappings (or in this case unmap it). Did you also get a chance to test `editWithVim`? How does that work for you?
