### ISSUE TITLE
Implement keyword searches

### ISSUE THREAD

**Issue by InconsolableCellist** [Jelmerro/Vieb#109] opened 2020-12-15 21:19 UTC
This is a big one for me. One of the best features of Firefox is "keyword searches" https://support.mozilla.org/en-US/kb/how-search-from-address-bar

Basically you go to any text input field, right click, and click "add a keyword for this search" and assign it a keyword, typically one or two letters. Later you then go into the location bar and type that keyword to search that field. 

E.g., go to YouTube.com, right click the field, click "add a keyword to this search" and assign it the keyword "yt". You can then type "yt TLJ sucked" and it'll take you to the search results on YouTube.com (https://www.youtube.com/results?search_query=tlj+sucked). Basically it does a keyword substitution in the query field of the GET request.

Once you start using this feature it's really hard to go back. Amazon, IMDB, RottenTomatoes, YouTube, Reddit, DuckDuckGo, StartPage, Google Maps, etc., all accessible with things like "a", "imdb", "rt", "yt", "r", etc. 

It's a massive time-saver and would be a really welcome feature.

**Comment by Jelmerro** [comment] 2020-12-15 21:23
This is a duplicate of #55. As I also mentioned in that issue, I recommend the use of [DuckDuckGo Bangs](https://duckduckgo.com/bang) for this.

**Closed by Jelmerro** 2020-12-15 21:23 UTC
Labels: duplicate, enhancement, mode-explore
