### ISSUE TITLE
Cannot navigate in PDF files

### ISSUE THREAD

**Issue by gebner** [Jelmerro/Vieb#91] opened 2020-11-21 18:21 UTC
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Electron opens PDF files in the built-in PDF viewer.  Keybindings such as `j`, etc. do not work in this viewer (which is implemented as a browser plugin).

If you go into insert mode and click on the PDF file, then arrow keys work.  But escape doesn't work (vieb doesn't see the keypress and doesn't exit insert mode)...

**To Reproduce**
Open a random PDF and try to scroll down using `j`:
https://www.medrxiv.org/content/10.1101/2020.11.18.20233122v1.full.pdf

**Expected behavior**
Viewing PDF files should work one way or another.

One option would be to make `j`, etc., work in the PDF plugin.

I'd also be happy if PDF files were downloaded and opened in the system PDF viewer.

**Specs**
 - OS: NixOS
 - Version: master

**Comment by gebner** [comment] 2020-11-21 18:25
It is surprisingly hard to disable the PDF plugin in electron: see https://github.com/electron/electron/issues/24334 and https://github.com/electron/electron/issues/24977

The first issue links to a workaround implemented in the min browser: https://github.com/minbrowser/min/commit/42fefc3eb534d819197643bead4f269bd4f8b384

**Comment by Jelmerro** [comment] 2020-11-21 18:26
I noticed this a while ago as well, but there seems to be no way to handle this currently. I should have made an issue for it back then. There are actually a lot of Electron issues related to the PDF plugin, but sadly there is no way to disable it currently.
https://github.com/electron/electron/issues/23392
https://github.com/electron/electron/issues/9030
https://github.com/electron/electron/issues/24977
https://github.com/electron/electron/issues/26054

**Comment by gebner** [comment] 2020-11-21 18:44
Would you be happy with a PR that adds (something like) the workaround in the min browser.  (With a `nopdfplugin` option?)  The PDF situation is really annoying me.

**Comment by Jelmerro** [comment] 2020-11-21 18:49
Just to confirm, this will disable the built-in PDF viewer and download the file instead? Because that sounds more like a solution than a workaround to me actually, and I wouldn't mind making it the default if that means one annoyance in Vieb. I would personally implement such a setting as: "pdfviewer" (default disabled/unset), which will enable this viewer only when people want it to, where the setting could include the reason why it's disabled by default.

**Comment by gebner** [comment] 2020-11-21 18:57
AFAICT it won't disable the built-in PDF viewer, but intercepts all responses with content-type `application/pdf` and (in our case) download the file instead.  I haven't tried it yet.

**Comment by Jelmerro** [comment] 2020-11-21 19:51
I have tested this workaround, and it doesn't work reliable, so I see no reason to add this. It's an Electron issue that you can't disable the PDF viewer, no doubt about it anymore if you ask me.

**Comment by Jelmerro** [comment] 2021-03-03 22:40
There is actually ANOTHER electron bug that is affecting Vieb related to the pdf viewer: https://github.com/electron/electron/issues/26714
This results in the pdf not even being rendered at all in recent Vieb versions. Which is ironically a pretty okay solution, but it's caused by another electron bug in this case, which seems to get more attention than the issue about disabling the pdf viewer...

**Comment by CMurtagh-LGTM** [comment] 2021-06-08 13:28
> I'd also be happy if PDF files were downloaded and opened in the system PDF viewer.

I have a solution to this, downloading the file and running zathura using `action.openLinkExternal`.

(Here)[https://github.com/CMurtagh-LGTM/dotfiles/blob/master/.local/bin/download_and_run.py] is a python script that does so and (here)[https://github.com/CMurtagh-LGTM/dotfiles/blob/master/.config/Vieb/zathura.sh] is a sh script that adds the arguments.

> AFAICT it won't disable the built-in PDF viewer, but intercepts all responses with content-type application/pdf and (in our case) download the file instead. I haven't tried it yet.

Would it be possible to have an option run a command instead?

**Comment by Jelmerro** [comment] 2021-06-08 15:53
Besides `openLinkExternal` there is also `action.downloadLink`. I think Vieb already has enough options to download or open PDF externally, the problem is here is that there still exist a viewer inside Vieb, even though we don't need it. The PDF viewer is [ currently broken](https://github.com/electron/electron/issues/26714), can't [be disabled](https://github.com/electron/electron/issues/24977) and [doesn't](https://github.com/electron/electron/issues/23392) support [custom shortcuts](https://github.com/electron/electron/issues/26054). There are no Vieb specific issues regarding PDF that I'm aware of, only the Electron issues mentioned above that are not Vieb's responsibility to fix, hence the "upstream issue" label on this issue. I would recommend to help them out if you know even the slightest bit of C++ code.

**Comment by Jelmerro** [comment] 2023-06-15 21:26
Sort of fixed in V10, the new release by default blocks the PDF viewer, but this can be controlled with `pdfbehavior`. Default behavior is to download the PDF, which I consider a valid workaround for this issue, at least until PDF interaction can be changed compared to the defaults in Electron.

**Closed by Jelmerro** 2023-06-15 21:26 UTC
Labels: bug, electron issue
