### ISSUE TITLE
One of the vieb instances in muti-datafolder setup stopped responding

### ISSUE THREAD

**Issue by i3d** [Jelmerro/Vieb#189] opened 2021-05-13 17:12 UTC
**Checklist**
- [ x] I searched the `:help` documentation using `/` for helpful information
- [ x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x ] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
So I have Vieb setup with two datafolders. One dedicated for my work, and the other for all other web surfing.
There are two completely different file directories on my Mac machine.
It was all working perfectly yesterday but this morning when I login the computer again, I thought one of them (my work instance) became like this: https://i.imgur.com/cujsvsS.png It does not respond to any keystrokes anymore, can't be killed (normally). From the screenshot, you could see that it seems under the "I" (insert mode) and somehow can't render anything else.
The other one is perfectly fine though. 

Some preliminary investigations:

1. commandline can't bring any difference to the zombie instance, nor --debug flag. There is no output of any sort of useful debug info... The only thing it outputs is "Sending urls to existing instance in /Users/jimxu/Library/Application Support/ViebChat/".
2. commandline to the other working Vieb instance does work, just as normal.
3. Using Mac default launcher to launch Vieb instance no longer works for both instances. (except for that the normal one can be launched from CLI)

**To Reproduce**
I am not really sure how this has been gotten into this state. And sorry I can't retain this broken state for long since I have to get it working so I will force kill it. But if there is any better debugging strategy, please let me know so that I could try them next time when this happens.

**Specs**
 - OS: MacOS 11.13.1
 - Version: 4.5.1

**Comment by Jelmerro** [comment] 2021-05-13 18:59
This typical gray background indicates a chromium crash. There is nothing that Vieb can do to prevent this, the same would have happened in similar circumstances when using any other Chromium based browser. Sorry to close the issue out like this, but that's basically all there is to it. Only thing you could try is exiting insert mode and closing the tab, because Vieb does handle crashing tabs pretty well: they turn red in the tabbar and you can close them, without losing other data. Though it could be beyond repair, and I hope this won't happen again, but again, this is a Chromium issue that can't be fixed by Vieb.

**Closed by Jelmerro** 2021-05-13 18:59 UTC
Labels: bug, upstream issue

**Comment by i3d** [comment] 2021-05-14 15:52
I see. Thanks for the info!

**Comment by Jelmerro** [comment] 2021-05-14 17:14
If you can make it reproducable there might be SOME things we can try to debug, but more often than not these issues are not actually Vieb related at all.
