### ISSUE TITLE
left mouse click does not follow link on the first click in fresh tabs

### ISSUE THREAD

**Issue by se7en-x230** [Jelmerro/Vieb#489] opened 2023-06-18 02:34 UTC
Since the update left click refreshes the page and does not follow the link. 
Keybinding f works find left click does not

**Comment by Jelmerro** [comment] 2023-06-18 12:16
I have only had this issue very occasionally, but then it does work if I click the link a second time. Is this also in line with your experience? I have not been able to find a fix for it as of yet.

**Comment by se7en-x230** [comment] 2023-06-18 13:02
Yes it is a very random thing. Sometimes it works sometimes not.

I generated a new config with my setup b cause I thought something is messing up but that did not solve the problem.

**Comment by se7en-x230** [comment] 2023-06-18 14:19
I moved the .config/vieb folder to generate a completely new one and tested now for 10 min.
No problems. So I guess it is something in the config file that causes the behavior.

**Comment by se7en-x230** [comment] 2023-06-18 14:24
https://0x0.st/HTjD.txt

that's my viebrc

**Comment by Jelmerro** [comment] 2023-06-18 15:05
I don't think it's the config specifically, but it might be related to other data in the folder. My viebrc is extremely minimal and I also have it, but only in my main instance with a lot of history and data, not in others. Could very well be the result of having some pieces of corrupted chromium data in there somewhere instead of being directly caused by a setting. I don't see any of these settings being related to the problem personally, as the only setting we share is the custom downloadpath... here's my config for comparison:
![image](https://github.com/Jelmerro/Vieb/assets/1696674/886b681a-d300-4b1b-bad0-7b1b3bd05ef8)
Are you seeing any errors in the internal devtools (opens with `F8`) when this happens? I do have some logs in there that could be related, I'll let you know when I know more.

**Comment by se7en-x230** [comment] 2023-06-18 15:29
I renamed the enter Vieb folder 
Opened Vieb to recreate the entries .config/Vieb folder.
Then tested a while without problems.
Next i copied my colors/ folder and vievrc into the new created Vieb folder and the problem restated again.

**Comment by se7en-x230** [comment] 2023-06-18 15:30
I will do further tests tomorrow morning

**Comment by Jelmerro** [comment] 2023-06-18 15:32
Okay, so I could reproduce this in a completely new Vieb datafolder: it's only doing this if you click on a link in a new tab that hasn't navigated through other means yet. If you use follow mode or explore mode to change the url of the tab and THEN click with the mouse it all keeps working, but if you make a new tab and the FIRST thing you do in it is click on a link then it doesn't work. If you then click on that same link again it does work and that tab will never have that issue again from what I have seen.

**Comment by Jelmerro** [comment] 2023-06-18 21:34
I believe to have found the reason for this issue, it's due to a call to the webview on each navigation to change the useragent, which was moved to a new spot in the V10 release, and apparently cancels navigations if called at this moment. After moving the call to the load-commit event instead of the will-navigate event it works again, see [this commit](https://github.com/Jelmerro/Vieb/commit/d0ff8993acd561096d3de93b7af2880c245cc88f) for the fix. If you know how to run from source, do let me know if this resolves the problem for you as well.

**Comment by Jelmerro** [comment] 2023-06-23 08:11
Fixed in 10.1.0 :tada:

**Closed by Jelmerro** 2023-06-23 08:11 UTC
Labels: bug, question
