### ISSUE TITLE
Allow for custom css / scripts

### ISSUE THREAD

**Issue by Caduser2020** [Jelmerro/Vieb#68] opened 2020-09-15 14:51 UTC
Firefox has extensions to allow adding custom JS or CSS for specific websites. Is this something that could be added to Vieb?

**Comment by Jelmerro** [comment] 2020-09-15 21:36
Yes, that's absolutely something that can and eventually should be added to Vieb. Though I'm wondering if this could be seen as a duplicate of #64. Greasemonkey scripts allow you to execute custom JavaScript (and thus insert CSS) for a set of pages based on different rules (as defined in the metadata section of the scripts). Feel free to let me know how this would differ (if at all) from the feature that you are proposing.

**Comment by Caduser2020** [comment] 2020-09-16 16:55
A Greasemonkey script is somewhat overkill for modifing a few CSS variables, but if that is easier to implement this can be closed as a duplicate.

**Comment by Jelmerro** [comment] 2020-09-16 22:36
Although it's not easier to implement, it feels redundant to have a custom CSS feature when Greasemonkey scripts can do exactly that with JavaScript and a few lines of metadata. I don't like having multiple ways to achieve basically the same thing. Also, the overall structure and seemingly simple API of Greasemonkey are something I don't want to build from scratch inside Vieb. I would much rather implement the API and let users make or import scripts using a familiar system like Greasemonkey.

**Closed by Jelmerro** 2020-09-16 22:36 UTC
Labels: duplicate, enhancement
