### ISSUE TITLE
Vieb does not start on MacOS Big Sur

### ISSUE THREAD

**Issue by kekscode** [Jelmerro/Vieb#114] opened 2020-12-24 15:02 UTC
**Describe the bug**

As discovered during testing of #113, Vieb does not start properly after an Update from MacOS Catalina to MacOS Big Sur. Before the upgrade to Big Sur vieb.app worked well under MacOS Catalina.

The following has been done to force different conditions and get more insight:

* Installing the vieb.app 3.1.0 release and double-clicking the vieb.app leads to a running application with a visible menubar, no main window and no way to close the application properly (not even with the menubar/quit menu). It has to be force-killed.
* Cloning the latest head from the main repository (3a81efb) and building+running the application according to the documentation, leads to the same result.
* Starting 3a81efb vieb with `npm start -- --debug` starts vieb with a web developer debug window and a disfunctional main window. At least the main window gets drawn on the screen now.
* Changing the the order of `.init()` calls in `app/apploader.js` helps to initialize the main window including the html rendering engine (even without the `--debug` flag), but this still does not solve all problems. E.g. a custom `.viebrc` settings file is not evaluated properly and errors in the dev console are still shown.

Here is the change which brings back most of the functionality while still not loading/evaluating everything correctly on startup:

```
❯ git diff origin/master
diff --git app/apploader.js app/apploader.js
index a059215..a26f0f3 100644
--- app/apploader.js
+++ app/apploader.js
@@ -46,11 +46,11 @@ window.addEventListener("DOMContentLoaded", () => {
     // Load the layout manager, for splitting multiple webviews
     window.PAGELAYOUT = require("./js/pagelayout")
     // Some modules require initialisation
+    window.TABS.init()
     window.INPUT.init()
     window.SETTINGS.init()
     window.SESSIONS.init()
     window.HISTORY.init()
-    window.TABS.init()
     window.FAVICONS.init()
     window.MODES.init()
     window.COMMANDHISTORY.init()
```

Some other things i tried but which did not change anything:

* Removing the custom `~/.viebrc` file
* Removing the ` ~/Library/Application\ Support/Vieb` directory
* Upgrading from electron 11.1.0 to 11.1.1

**To Reproduce**

See the bug description.

**Expected behavior**

Vieb startup without any errors in the debug console, proper loading of all its modules/functionality (`app/apploader.js`) and application of all options in a given custom configuration file.

**Specs**

 - OS: macOS Big Sur
 - Version: 11.1

I have not the electron/js knowhow needed to debug this issue systematically, but i am more than happy to help to fix this issue, because i really want to use vieb. So please don't hesitate to contact me to fix this issue.

**Comment by Jelmerro** [comment] 2020-12-24 15:24
Re-ordering parts of the setup isn't recommended. This order is required, as most entries that are initialized later, require parts of the earlier components. The reason why you get the tabbar only when doing this, is because the problem isn't in `tabs.js`, but happens before that. As I briefly mentioned in our earlier discussion, my guess seems to be that for it can't find the current tab. For some reason it tries to access those before they are initialized, which only happens on Big Sur from what I have seen so far. I'll keep investigating the error log you send me, I'll paste it below for others as a reference:

```
01:25:57.243 /Users/REDACTED/devops/Vieb/app/js/settings.js:450 Uncaught TypeError: Cannot read property 'getAttribute' of null
   at updateContainerSettings (/Users/REDACTED/devops/Vieb/app/js/settings.js:450)
   at Object.set (/Users/REDACTED/devops/Vieb/app/js/settings.js:707)
   at Object.set (/Users/REDACTED/devops/Vieb/app/js/command.js:108)
   at Object.execute (/Users/REDACTED/devops/Vieb/app/js/command.js:696)
   at loadFromDisk (/Users/REDACTED/devops/Vieb/app/js/settings.js:657)
   at Object.init (/Users/REDACTED/devops/Vieb/app/js/settings.js:186)
   at /Users/REDACTED/devops/Vieb/app/apploader.js:50
01:30:01.756 /Users/REDACTED/devops/Vieb/app/js/command.js:259 Uncaught (in promise) TypeError: Cannot read property 'src' of null
   at openSpecialPage (/Users/REDACTED/devops/Vieb/app/js/command.js:259)
   at Object.help (/Users/REDACTED/devops/Vieb/app/js/command.js:272)
   at Object.execute (/Users/REDACTED/devops/Vieb/app/js/command.js:696)
   at Object.useEnteredData (/Users/REDACTED/devops/Vieb/app/js/actions.js:324)
   at doAction (/Users/REDACTED/devops/Vieb/app/js/input.js:571)
   at executeMapString (/Users/REDACTED/devops/Vieb/app/js/input.js:512)
   at handleKeyboard (/Users/REDACTED/devops/Vieb/app/js/input.js:640)
openSpecialPage @ /Users/REDACTED/devops/Vieb/app/js/command.js:259
help @ /Users/REDACTED/devops/Vieb/app/js/command.js:272
execute @ /Users/REDACTED/devops/Vieb/app/js/command.js:696
useEnteredData @ /Users/REDACTED/devops/Vieb/app/js/actions.js:324
doAction @ /Users/REDACTED/devops/Vieb/app/js/input.js:571
executeMapString @ /Users/REDACTED/devops/Vieb/app/js/input.js:512
handleKeyboard @ /Users/REDACTED/devops/Vieb/app/js/input.js:640
async function (async)
executeMapString @ /Users/REDACTED/devops/Vieb/app/js/input.js:512
handleKeyboard @ /Users/REDACTED/devops/Vieb/app/js/input.js:640
01:30:10.137 /Users/REDACTED/devops/Vieb/app/js/tabs.js:829 Uncaught (in promise) TypeError: Cannot read property 'isCrashed' of null
   at Object.navigateTo (/Users/REDACTED/devops/Vieb/app/js/tabs.js:829)
   at Object.useEnteredData (/Users/REDACTED/devops/Vieb/app/js/actions.js:355)
   at doAction (/Users/REDACTED/devops/Vieb/app/js/input.js:571)
   at executeMapString (/Users/REDACTED/devops/Vieb/app/js/input.js:512)
   at handleKeyboard (/Users/REDACTED/devops/Vieb/app/js/input.js:640)
navigateTo @ /Users/REDACTED/devops/Vieb/app/js/tabs.js:829
useEnteredData @ /Users/REDACTED/devops/Vieb/app/js/actions.js:355
doAction @ /Users/REDACTED/devops/Vieb/app/js/input.js:571
executeMapString @ /Users/REDACTED/devops/Vieb/app/js/input.js:512
handleKeyboard @ /Users/REDACTED/devops/Vieb/app/js/input.js:640
async function (async)
executeMapString @ /Users/REDACTED/devops/Vieb/app/js/input.js:512
handleKeyboard @ /Users/REDACTED/devops/Vieb/app/js/input.js:640
01:30:11.974 /Users/REDACTED/devops/Vieb/app/js/tabs.js:829 Uncaught (in promise) TypeError: Cannot read property 'isCrashed' of null
   at Object.navigateTo (/Users/REDACTED/devops/Vieb/app/js/tabs.js:829)
   at Object.useEnteredData (/Users/REDACTED/devops/Vieb/app/js/actions.js:355)
   at doAction (/Users/REDACTED/devops/Vieb/app/js/input.js:571)
   at executeMapString (/Users/REDACTED/devops/Vieb/app/js/input.js:512)
   at handleKeyboard (/Users/REDACTED/devops/Vieb/app/js/input.js:640)
navigateTo @ /Users/REDACTED/devops/Vieb/app/js/tabs.js:829
useEnteredData @ /Users/REDACTED/devops/Vieb/app/js/actions.js:355
doAction @ /Users/REDACTED/devops/Vieb/app/js/input.js:571
executeMapString @ /Users/REDACTED/devops/Vieb/app/js/input.js:512
handleKeyboard @ /Users/REDACTED/devops/Vieb/app/js/input.js:640
async function (async)
executeMapString @ /Users/REDACTED/devops/Vieb/app/js/input.js:512
handleKeyboard @ /Users/REDACTED/devops/Vieb/app/js/input.js:640
01:31:08.267 /Users/REDACTED/devops/Vieb/app/js/command.js:259 Uncaught (in promise) TypeError: Cannot read property 'src' of null
   at openSpecialPage (/Users/REDACTED/devops/Vieb/app/js/command.js:259)
   at Object.help (/Users/REDACTED/devops/Vieb/app/js/command.js:272)
   at Object.execute (/Users/REDACTED/devops/Vieb/app/js/command.js:696)
   at Object.useEnteredData (/Users/REDACTED/devops/Vieb/app/js/actions.js:324)
   at doAction (/Users/REDACTED/devops/Vieb/app/js/input.js:571)
   at executeMapString (/Users/REDACTED/devops/Vieb/app/js/input.js:512)
   at handleKeyboard (/Users/REDACTED/devops/Vieb/app/js/input.js:640)
openSpecialPage @ /Users/REDACTED/devops/Vieb/app/js/command.js:259
help @ /Users/REDACTED/devops/Vieb/app/js/command.js:272
execute @ /Users/REDACTED/devops/Vieb/app/js/command.js:696
useEnteredData @ /Users/REDACTED/devops/Vieb/app/js/actions.js:324
doAction @ /Users/REDACTED/devops/Vieb/app/js/input.js:571
executeMapString @ /Users/REDACTED/devops/Vieb/app/js/input.js:512
handleKeyboard @ /Users/REDACTED/devops/Vieb/app/js/input.js:640
async function (async)
executeMapString @ /Users/REDACTED/devops/Vieb/app/js/input.js:512
handleKeyboard @ /Users/REDACTED/devops/Vieb/app/js/input.js:640
```

**Comment by Jelmerro** [comment] 2020-12-24 16:15
I believe my latest commit on master should solve at least some of these errors, but I don't think these are possible without a viebrc config file. Can you make sure you moved the global viebrc files as well: `~/.viebrc` and `~/.vieb/viebrc`. If those don't exist, you can also try a separate datafolder: `npm start -- --debug --datafolder ViebData` for example.

Please try starting Vieb again with `npm start -- --debug` from the latest master commit and post the debug errors here again. I hope we can solve all issues on Big Sure this way.

**Comment by kekscode** [comment] 2020-12-27 11:42
I started latest master (6fe8dc1e4e418a997cb0838e251f4719ae7fd7d1) and did a fresh `npm install` and after that i start vieb with `npm start -- debug` and provided a viebrc file under: `~/.viebrc`.

The viebrc is:

```
" Options
set adblocker=update
set cache=clearonquit
set noclearcookiesonquit
set nocleardownloadsoncompleted
set nocleardownloadsonquit
set noclearhistoryonquit
set noclearlocalstorageonquit
set noclosablepinnedtabs
set containercolors=temp\d+~#ff0
set containerkeeponreopen
set containernewtab=s:usecurrent
set containershowname=automatic
set containersplitpage=s:usecurrent
set containerstartuppage=main
set countlimit=100
set darkreader
set devtoolsposition=window
set downloadmethod=automatic
set downloadpath=~/Downloads/
set favicons=session
set favoritepages=
set firefoxmode=google
set fontsize=14
set guifullscreennavbar=oninput
set guifullscreentabbar=onupdate
set guihidetimeout=2000
set guinavbar=always
set guitabbar=always
set keeprecentlyclosed
set ignorecase
set incsearch
set maxmapdepth=10
set mintabwidth=28
set mouse
set mousefocus
set nomousenewtabswitch
set nonativenotification
set notificationduration=6000
set nonotificationforpermissions
set notificationposition=bottomright
set permissioncamera=ask
set permissionclipboardread=ask
set permissionclosepage=allow
set permissionfullscreen=allow
set permissiongeolocation=ask
set permissionmediadevices=ask
set permissionmicrophone=ask
set permissionmidi=ask
set permissionmidisysex=ask
set permissionnotifications=ask
set permissionopenexternal=ask
set permissionpersistentstorage=ask
set permissionpointerlock=block
set permissionsallowed=
set permissionsblocked=
set permissionunknown=block
set redirects=https?://(www\.)?google\.com(\.\w+)?/amp/s/amp\.(.*)~https://$3
set noredirecttohttp
set requesttimeout=20000
set restoretabs
set restorewindowmaximize
set restorewindowposition
set restorewindowsize
set search=https://google.com/search?q=%s
set showcmd
set spell
set spelllang=system
set nosplitbelow
set nosplitright
set startuppages=
set storenewvisits
set suggestcommands=1000
set suggestfiles=all
set nosuggestfilesfirst
set suggestexplore=20
set suggesttopsites=10
set tabcycle
set tabnexttocurrent
set taboverflow=scroll
set timeout
set timeoutlen=1000
set vimcommand=gvim
set windowtitle=simple
```

Now the following happens:

1. Vieb startup is a lot faster than before and the configfile is used (settings get applied, tabs are restored)
1. A bit strange is that my blocklists are updated 2-3 times at startup according to the messages (see screenshot; bottom right)
1. No error messages on the console anymore at startup. I did some surfing, ex commands (switching colorschemes e.g.), etc. Nothing showed anything in the console which is of course great, but of course this is not proper testing. Do you have any recommendations what i should test to hit some critical code paths in order to get proper testing done?
1. A quick test with `npm start -- --debug --datafolder` (while keeping the above viebrc) showed the same behaviour as before which is good i guess :)

Minor issue, just for info: Stdout/Stderr shows repeatedly this message after startup: `(node:89904) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information`

![image](https://user-images.githubusercontent.com/803252/103169769-10fba980-483f-11eb-8ad2-a76106709205.png)

**Comment by kekscode** [comment] 2020-12-27 12:08
I just found one debug message on the debug console window, but i don't know how to reproduce it yet:

```
13:05:15.137 electron/js2c/renderer_init.js:103 Uncaught (in promise) Error: Error invoking remote method 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error: ERR_ABORTED (-3) loading 'https://www.<redacted>.de/'
    at EventEmitter.o.invoke (electron/js2c/renderer_init.js:103)
o.invoke @ electron/js2c/renderer_init.js:103
async function (async)
o.invoke @ electron/js2c/renderer_init.js:103
parse @ electron/js2c/renderer_init.js:123
SrcAttribute.handleMutation @ electron/js2c/renderer_init.js:123
handleWebviewAttributeMutation @ electron/js2c/renderer_init.js:131
attributeChangedCallback @ electron/js2c/renderer_init.js:127
setValue @ electron/js2c/renderer_init.js:123
set @ electron/js2c/renderer_init.js:123
navigateTo @ /Users/stefanantoni/devops/Vieb/app/js/tabs.js:840
useEnteredData @ /Users/stefanantoni/devops/Vieb/app/js/actions.js:355
doAction @ /Users/stefanantoni/devops/Vieb/app/js/input.js:571
executeMapString @ /Users/stefanantoni/devops/Vieb/app/js/input.js:512
handleKeyboard @ /Users/stefanantoni/devops/Vieb/app/js/input.js:640
```

**Comment by Jelmerro** [comment] 2020-12-27 12:52
Regarding the contextIsolation, that's just a warning that the defaults will change in the next electron version. I already explicitly set them in Vieb, so there should be no issue. See [here](https://github.com/electron/electron/issues/26785) for the related electron issue.

I have no answer as of yet to the duplicate updating. The logic for the updater is a bit dated, it should probably be reworked to prevent this from happening.

The remote invocation error happens when the loading gets aborted in an unexpected way. I have yet to reproduce it reliably myself. Though I don't think it really matters, as it doesn't seem to affect or break any functionality.

I'll close this issue as you were able to start Vieb on Big Sur. From what I understand it had more to do with the containercolors setting than Big Sur, but since the issue is resolved I'll close it anyway.

**Closed by Jelmerro** 2020-12-27 12:52 UTC
Labels: bug, help wanted, question
