### ISSUE TITLE
Normal mode navigation keybindings don't work on certain websites

### ISSUE THREAD

**Issue by mplanchard** [Jelmerro/Vieb#175] opened 2021-04-30 15:42 UTC
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**

For certain websites, including:

- https://chrome.google.com/webstore/detail/1password-–-password-mana/aeblfdkhhhdcdjpifhhbdiojplfjncoa
- https://groups.google.com/g/mu-discuss/c/ukEaGmcCmSE?pli=1
- the confluence overview at https://mydomain.atlassian.net/wiki/home

the navigation keyborad bindings (e.g. j, k, C-u, C-d, etc.) are nonfunctional. 
Follow mode still works, and navigation with the mouse still works.

**To Reproduce**
Navigate to one of those sites, press `j` or `k`

**Expected behavior**
Navigation actions triggered via keybindings work

**Specs**
 - OS: Ubuntu 20.04
 - Version: 4.5.1

**Comment by mplanchard** [comment] 2021-04-30 16:08
Also seeing this at https://groups.google.com/g/mu-discuss/c/ukEaGmcCmSE?pli=1 for example. I'll continue to update the issue description with any other sites I encounter.

**Comment by Jelmerro** [comment] 2021-04-30 16:44
Duplicate of #150, see `:h scrolling`.

**Closed by Jelmerro** 2021-04-30 16:44 UTC
Labels: question, wontfix

**Comment by mplanchard** [comment] 2021-04-30 16:57
Ah sorry my search terms didn't turn anything up. Thanks for the link!
