### ISSUE TITLE
How to deal with pop up blocker(s) in relation to vieb

### ISSUE THREAD

**Issue by garycoy** [Jelmerro/Vieb#73] opened 2020-09-29 20:21 UTC
Hello - 

Just started using vieb and love it.  Only one issue so far. Any website that uses a pop up seems to automatically get blocked for allowing the pop up page. I hate pop ups but sometimes they are avoidable. For example I use Oracle Enterprise Manager at work - and it is dysfunctional in vieb (I blame OEM).

Remedy (work-hosted BMC Remedy) same issues. How do I enable pop ups from certain domains?

I don't think I have any 'external' pop up blockers.  Seems like vieb is doing the blocking.

**Comment by Jelmerro** [comment] 2020-09-29 21:53
This is a duplicate of #67 and seems highly unlikely to be picked up, as Electron does not offer options to allow site specific popups. It's either all or none, and even then you would need to re-open tabs to change such a setting. Again, see #67 for more details.

**Closed by Jelmerro** 2020-09-29 21:53 UTC
Labels: duplicate
