### ISSUE TITLE
Making screenshots

### ISSUE THREAD

**Issue by ottopiramuthu** [Jelmerro/Vieb#220] opened 2021-06-12 11:42 UTC
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Addition or change**
Add a command to screenshot the current page (without the UI). 

A really nice addition to this request that is in [surfingkeys](https://github.com/brookhong/Surfingkeys) is taking a screenshot of the full page with `yG`:

https://user-images.githubusercontent.com/49997309/121774682-8c34eb80-cb51-11eb-91ee-dca709a912cf.mp4

This is convenient as you can quickly copy/save the image, but it isn't necessary as `:print`ing the page to a PDF and creating an image from that works as well.

**Alternatives considered**
Using an external screenshot program works, but the command would avoid having to drag the borders to the page.

**Comment by Jelmerro** [comment] 2021-09-06 21:29
Making a screenshot of the entire page is not supported, but saving just the visible parts is possible and has just been added.

**Comment by ottopiramuthu** [comment] 2021-09-06 21:38
This works, only it saves the PNG with a transparent background. This might not be what most people expect.

**Comment by Jelmerro** [comment] 2021-09-06 21:43
Seems like this is intended behavior, it seems to depend on the webpage: https://github.com/electron/electron/issues/29289

**Comment by ottopiramuthu** [comment] 2021-09-06 21:49
That's fine then. I tested this with the Vieb help page, and it would be nice if Vieb's internal pages had a `background-color` property to prevent the transparency.

**Comment by ottopiramuthu** [comment] 2021-09-07 00:13
I'm getting the error "Something went wrong saving the image" whenever I don't give the command a filename.
- `:open google.com`
- `:screenshot` or
- `:screenshot ~/Desktop/` don't work
- `:screenshot ~/Desktop/s.png` does.

**Comment by Jelmerro** [comment] 2021-09-07 21:22
I suspect that you tested this on Windows, apparently `:` is not allowed inside the filename... I have changed it something else, let me know if it's fixed now, and if not, what you see in the output of `:internaldevtools`.

**Comment by ottopiramuthu** [comment] 2021-09-07 22:13
This works, thank you!

**Comment by Jelmerro** [comment] 2021-09-08 17:42
Entire page screenshot is not supported by Electron, so we can't fix that sadly.

**Closed** 2021-09-08 17:53 UTC
Labels: enhancement, gui
