### ISSUE TITLE
Solving Captchas and Logging into google

### ISSUE THREAD

**Issue by 3hree6ix0** [Jelmerro/Vieb#251] opened 2021-06-25 02:39 UTC
I Switched to vieb a few days ago and since then im having isses logging into google. When captchas appear i am not able to solve them by going into follow mode. I tried other modes as well. 
Is this a bug. If yes then is there a workaround.
Thanks!

OS- Artix
WM- bspwm

**Comment by theolice** [comment] 2021-06-25 10:45
Have you tried playing with the `:set firefoxmode` setting? By default this is set on `never`, which can be the cause of your problem.
Try setting it to either `always` or `google` and check if that fixed your problem by any chance.

I believe this is also mentioned in the [FAQ page](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md) in the "How does it compare to other plugins and browsers?" section.

**Comment by Jelmerro** [comment] 2021-06-25 16:06
Already answered in the FAQ indeed as @theolice mentions, see [this FAQ entry in particular](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md#why-cant-i-sign-in-to-google). The short version is that Vieb has a few settings that can make login into Google easier, it seems to work for pretty much everyone I have heard back from, so I'll be closing this issue because of it. And in case it doesn't work, there is nothing Vieb can do to change this. They can still block you (and even block regular Chrome users) whenever they want to, it's a Google account, they own it, not you, it's literally in their terms of service.

**Closed by Jelmerro** 2021-06-25 16:06 UTC
Labels: duplicate, wontfix, workaround
