### ISSUE TITLE
Microsoft Office Excel web app not responsive to input

### ISSUE THREAD

**Issue by mr-majkel** [Jelmerro/Vieb#340] opened 2021-12-17 14:48 UTC
Hi, this is a strange issue. It seems that online version of excel is not accepting inputs from the keyboard (i.e. editing cells is not working) no matter if I'm in Normal or Insert mode.

Running Vieb 6.2,0. on Windows 10.

**Comment by Jelmerro** [comment] 2021-12-17 16:39
Are there any errors in the console we could use as a starting point? Because as is this issue is not something I can just pick up and fix, as I have never had this problem. Are you sure you have entered insert mode and put focus on the cell, worst case by using the mouse, to test it properly? Please let me know in more detail what you tried.

**Comment by mr-majkel** [comment] 2021-12-17 17:20
Hi @Jelmerro, thanks for a quick response. You have given me some good hints in your questions. Previously, I have tried to input the data only with the keyboard. I was:
- entering pointer mode, 
- hovering over a cell, 
- pressing enter to get it focused (this works), 
- pressing 'i' to get to insert mode
- pressing other keys to enter values (this doesn't work)

Now I have just tried clicking with mouse (in insert mode) and only then I can actually edit the cell. Not ideal, but probably it is the Excel app that is not allowing to enter characters with just insert mode.

Overall it is still an improvement for me - I can continue to use Vieb, just not for Excel editing.

**Comment by Jelmerro** [comment] 2021-12-17 17:44
This is the right way to put focus to elements that refuse it via follow mode, but if that still doesn't work it's not something we can easily solve. Your method simulates a mouse click while putting focus on the page, that's about all we can do automatically I think :frowning_face: .

**Comment by Jelmerro** [comment] 2022-01-09 21:42
Could you try the latest development version from git? I made some changes to the focus code that might fix this issue for you, I can't test it myself as I don't have a Microsoft account.

**Comment by Jelmerro** [comment] 2022-01-30 13:33
I believe this specific case to be fixed in the 7.x.x series of releases, so I'm going to close this for now. For others finding this issue, the steps above are the proper way to set focus to a specific point on the page, if it doesn't work, most of the time it's caused by the site not allowing us to do so.

**Closed by Jelmerro** 2022-01-30 13:33 UTC
Labels: question

**Comment by mr-majkel** [comment] 2022-02-01 09:42
Hi @Jelmerro sorry for not replying earlier. Just to let you know that I have just updated to 7.0.0 and unfortunately the input mode on focused cell in Excel web app is still not allowing to update the cell's contents - a mouse click is required.
