### ISSUE TITLE
First time load of github has no styling

### ISSUE THREAD

**Issue by run2cmd** [Jelmerro/Vieb#426] opened 2022-10-19 07:05 UTC
**Checklist**
- [ x ] I searched the `:help` documentation using `/` for helpful information
- [ x ] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [ x ] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
I've encountered a random problem. Very ofter it happens that after fresh start of Vieb I get pages loaded in a broken way. Here is screenshoot:

![github png](https://user-images.githubusercontent.com/9575150/196616570-1067d359-af4f-4538-97fc-d9e47fc70cf3.jpg)

This mostly happen only when I enter website for 1st time after Vieb start. Simple refresh fixes the problem, and I do not get this issue after going to site again with the same Vieb session.

Now  I describe it random as this happen with some websites and does not happen with others (example: youtube.com loads properly always). For me github.com loads properly only 1 out of 5 cases.

Log during the problem, however I do not know if it is relevant.:

```
[22376:1019/084304.232:ERROR:entry_impl.cc(1072)] No file for 8000886e
[22376:1019/084304.234:ERROR:entry_impl.cc(1072)] No file for 80008870
[22376:1019/084304.238:ERROR:entry_impl.cc(1072)] No file for 80008874
[22376:1019/084304.261:ERROR:entry_impl.cc(1072)] No file for 8000886b
[22376:1019/084304.262:ERROR:entry_impl.cc(1072)] No file for 8000886a
[22376:1019/084304.532:ERROR:entry_impl.cc(1072)] No file for 8000886d
```

**To Reproduce**
1. Start fresh instance of Vieb
2. Got to https://github.com

**Expected behavior**
Pages load properly when entered anytime.

**Specs**
 - OS: Windows 10
 - Version: 10.0.19044 Build 19044

**Comment by run2cmd** [comment] 2022-11-08 08:16
Setting to `cache=full` did help indeed.

**Comment by Jelmerro** [comment] 2022-11-08 10:03
Then it appears that the cache is not correctly wiped on windows, as another user reported #434 which seems to suggest that the cache gets corrupted by clearing it on Windows.

**Comment by Melandel** [comment] 2022-11-20 12:08
I was able to find the commit that created that behaviour: e3fe2e4b0fe89564a90f2cbeb04fff4c135fdb16 - `use nodejs fs api instead of rimraf`. I hope this helps.

From the logs, I also confirm that cache errors trigger the lack-of-styling behaviour.

**Comment by Jelmerro** [comment] 2022-11-21 19:00
Thanks a lot for finding the exact commit this was introduced, that helps a lot as you can imagine! I was just wondering if you also have this problem when running from source, and how reliably you can test this, because I might have found the problem, but if you don't have this issue when running from source I'll make a test build for you.

**Comment by Melandel** [comment] 2022-11-21 20:20
I reproduced by building each commits from source, if that can help

**Comment by Jelmerro** [comment] 2022-11-21 21:04
Could you please test if this change fixes these issues for you on Windows? I can't reproduce it on Linux and the one Windows machine here does not have this issue.
```diff
diff --git a/app/util.js b/app/util.js
index cf02711..71c299b 100644
--- a/app/util.js
+++ b/app/util.js
@@ -862,7 +862,9 @@ const modifiedAt = loc => {
     }
 }
 
-const rm = loc => fs.rmSync(loc, {"force": true, "recursive": true})
+const rm = loc => fs.rmSync(loc, {
+    "force": true, "maxRetries": 5, "recursive": true, "retryDelay": 100
+})
 
 const clearTempContainers = () => {
     const partitionDir = joinPath(appData(), "Partitions")
```

**Comment by Melandel** [comment] 2022-11-21 22:06
The suggested diff did not fix the issue (and makes the app take about 25 seconds to quit, on a side note)

**Comment by Jelmerro** [comment] 2022-11-21 22:14
This confirms that deleting those files does not work on Windows, for whatever reason. Either because the files are still open (though that should be solved by increasing the retry count), or because they stay opened long after Vieb is closed. I know that Windows is notoriously bad in file handling, but that does not explain why it used to work before. The node `rm` implementation is taken from the rimraf module, so it's basically the same code that's being run, only the arguments are different (the defaults in rimraf being 3 retries max, and 0 in nodejs, hence my request to test it with more retries). I'm out of ideas on how to solve it, if Windows simply refuses to delete these files than all I can recommend is keep the cache with `:set cache=full`. Could you try to figure out which of [these removals](https://github.com/Jelmerro/Vieb/blob/master/app/util.js#L874) is taking so long and/or is not working on Windows?

**Comment by Melandel** [comment] 2022-11-21 22:25
It's [this](https://github.com/Jelmerro/Vieb/blob/master/app/util.js#L887-L889) one.

Trying with the maxRetries/retryDelay now.

**Comment by Melandel** [comment] 2022-11-21 22:30
> The node `rm` implementation is taken from the rimraf module, so it's basically the same code that's being run, only the arguments are different

Doesn't it mean that `rimraf` does some additional things somewhere that make it work on Windows?

Also; https://nikola-breznjak.com/blog/javascript/nodejs/how-to-delete-node_modules-folder-on-windows-machine/

Maybe this is the problem?

**Comment by Melandel** [comment] 2022-11-21 22:35
Using `maxRetries: 100` and `retryDelay: 10` I get `[332:1121/232840.848:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is` and the process does not stop.

**Comment by Melandel** [comment] 2022-11-21 22:55
I tried something VERY clunky on the side (an attempt to use rimraf even though I don't understand anything about nodejs haha), it's [here](https://github.com/Jelmerro/Vieb/compare/master...Melandel:Vieb:attempt-to-reuse-rimraf) and removes the issue.

Trying your suggestion now!

**Comment by Melandel** [comment] 2022-11-21 22:58
Using your suggestion `const rm = f => {const rf = require("rimraf").sync;rf(f)}`, the process seems to have difficulties ending

**Comment by Melandel** [comment] 2022-11-21 23:02
Ha!

It does work though, if I use
```js
const rm = f => {const rf = require("rimraf").sync;
 try {
 rf(f)
 } catch {
  // Maybe permission errors?
 }
}
```

**Comment by Melandel** [comment] 2022-11-21 23:05
I am also able to confirm that

```js
const rm = loc => {
 try {
  fs.rmSync(loc, {"force": true, "recursive": true})
 } catch {
  //Ha...
 }
}
```

does NOT solve the issue

**Comment by Jelmerro** [comment] 2022-11-21 23:05
Thanks for confirming this! So the problem isn't in the new code per se, but specifically in the differences between node's rimraf and the actual mode, that much is now confirmed. In that case, could you try to make a file at `app/rimraf.js` with the following contents: [rimraf.js.txt](https://github.com/Jelmerro/Vieb/files/10061197/rimraf.js.txt)
And change your snippets code to the following:
```js
const rm = f => {const rf = require("./rimraf");
 try {
   rf(f)
 } catch {
  // Maybe permission errors indeed
 }
}
```
Does it still work then?

**Comment by Melandel** [comment] 2022-11-21 23:08
It does 😃

**Comment by Jelmerro** [comment] 2022-11-21 23:13
Alright, so in that case I can choose to either use the rimraf dependency again, or integrate this slim rework and use that. The main reason for removing rimraf was the required glob dependency and the fact that node seemed to be able to do this natively from 14 onwards, but I guess it's not Windows ready yet :sweat_smile: I will probably add this reworked version of rimraf, as it's a lot smaller, and will not break the light builds (which do not install any dependencies, as since the removal of rimraf we have no required ones for Vieb, and I don't want to add back rimraf as a required dependency including glob, because we just need a small section of the module that handles the Windows retry stuff). I'll try to see how much smaller/faster I can make the code now that it works.

**Comment by Melandel** [comment] 2022-11-21 23:16
Thank you for your time and energy !

**Comment by Jelmerro** [comment] 2022-11-21 23:17
Thanks to you as well for trying out all the suggestions so fast!

**Comment by Jelmerro** [comment] 2022-11-21 23:41
So just to confirm, the [code that I just pushed](https://github.com/Jelmerro/Vieb/commit/5ffb37f870dfafce6da882ee5ddaa3624283be00) fixes this issue on your machine right? Or did you require the try catch around the rf function?

**Comment by Melandel** [comment] 2022-11-21 23:44
The process seems to have difficulties terminating after that change 😢

**Comment by Jelmerro** [comment] 2022-11-21 23:45
In that case the try catch seems required, I'll add it.

**Comment by Jelmerro** [comment] 2022-11-21 23:46
Is it better if you `git pull` now?

**Comment by Melandel** [comment] 2022-11-21 23:47
I confirm this works!

**Comment by Jelmerro** [comment] 2022-11-21 23:48
Glad to hear that, I'll close the issue since it's now finally fixed :tada:

**Closed by Jelmerro** 2022-11-21 23:48 UTC
Labels: bug
