### ISSUE TITLE
Can not login in protonmail on 6.1.0-dev

### ISSUE THREAD

**Issue by KunaPrime** [Jelmerro/Vieb#319] opened 2021-09-18 01:12 UTC
**Checklist**

- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
on latest build logging in protonmail account is impossible due "invalid character error". Worked on previous version (6.0.0-dev)

**To Reproduce**
1. build new vieb (6.1.0-dev)
2. go to https://account.protonmail.com/login
3. enter username and password
4. red popup shows "invalid character" error

note: username and password contains only ASCII characters (no special unicode code points and are only a-z, A-Z and 0-9)
same credentials correctly works on firefox and on chromium.

**Expected behavior**
no error, successful login

**Specs**
 - OS: ubuntu 20.04.3
 - Version: vieb 6.1.0-dev (installed form deb package after build), electron (15.0.0-beta.6), Chromium 94.0.4606.31

**Comment by Jelmerro** [comment] 2021-09-18 20:20
I noticed this too, reported a bug to protonmail, they said to try with Firefox instead. The support has been incredibly unhelpful in this regard, and keeps asking the same questions about trying without extensions or clearing localstorage etc.

The other option I explored for solving this issue is of course looking for the cause myself, which turned out to be the conextIsolation property of Electron. I made a bug report for it [here](https://github.com/electron/electron/issues/31018) where we can further track the progress. There is nothing Vieb can do to solve this for now, it's not our bug.

**Comment by Jelmerro** [comment] 2022-01-13 21:33
So while it seems that this won't be fixed for a while in Electron, I did find out what was causing this: a broken atob/btoa implementation being used if contextIsolation is disabled. I have now written a custom implementation that works with a wider range of characters, which means you can now login to protonmail again! For now it's only in the code, but I'll release the next stable version in a few days from now.

**Closed by Jelmerro** 2022-01-13 21:33 UTC
Labels: bug, workaround, electron issue

**Comment by skunkfox** [comment] 2022-09-08 12:42
This appears to be an issue again.
