### ISSUE TITLE
scrolling not working on sites where it should

### ISSUE THREAD

**Issue by TuM0xA-S** [Jelmerro/Vieb#279] opened 2021-08-23 21:56 UTC
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)
- [x] i read man and look on some issues so i know about "not entire page scrollable websites"

**Describe the bug**
when surfing reddit and clicking on posts i had scroll actions not working. 
nor keybindings(j,k,gg,G) nor scroll actions (call &lt;scrollDown&gt;, call &lt;scrollBottom&gt; etc) not working
if i reload page it becomes scrollable again

**To Reproduce**
1) go to https://www.reddit.com/r/vieb/comments/p5zban/does_ublock_origin_work_currently/
2) scroll to "More posts from the vieb community" section
3) click on post
4) now scrolling not working

**Expected behavior**
scroll works normally without reloading

**Specs**
 - OS: Ubuntu 21.04 x86_64, window manager: spectrwm
 - Version: 5.3.0

**Comment by Jelmerro** [comment] 2021-08-23 22:21
Reddit is a mess when it comes to scrolling, sometimes they make the page scroll-able, sometimes they don't. Vieb's scrolling works by scrolling the page, unless you are using the pointer scroll actions, which will execute a scroll action the pointer position. There are no other methods of scrolling possible, because which of the potentially unlimited scroll-able section of the page should it scroll if you just ask it to scroll the page? The answer is that no scrolling will happen. This is also explained in the help page at `:h scrolling`. Duplicate of https://github.com/Jelmerro/Vieb/issues/150.

**Closed by Jelmerro** 2021-08-23 22:21 UTC
Labels: duplicate, question, mode-pointer

**Comment by TuM0xA-S** [comment] 2021-08-23 22:38
ok, but it seems strange that after reload scrolls working

**Comment by Jelmerro** [comment] 2021-08-23 22:42
If you look closely at the scrollbar, it's actually not full height before reloading, but it is afterwards. This is a quirk of the new reddit layout. You can also map the pointer scrolling actions to normal mode if you want to, but keep in mind that the pointer position is still used for the scroll action. I personally use old.reddit and haven't found other sites where this is as buggy as on the new reddit.

**Comment by TuM0xA-S** [comment] 2021-08-23 22:51
lol it is really not full height. modern web never ceases to amaze(of its stupidity). 
(btw your browser is best of vim-like browsers as for me)
