### ISSUE TITLE
Respecting open in new tab when clicking links

### ISSUE THREAD

**Issue by ipod825** [Jelmerro/Vieb#59] opened 2020-06-02 17:13 UTC
Currently on single mouse click, Vieb seems to always open the link in the current window. But Vieb should respect the link attribute if it is configured to be opened in a new tab.

**Comment by Jelmerro** [comment] 2020-06-02 19:06
This is by design, if you want to open the link in a new tab, just use middle mouse button, or preferably, start the version of follow mode that opens links in a new tab. This way there is no guessing as to what the page will do when clicking on a link, but instead the choice is always left up to the user.

I'm closing this issue for this reason. Please explain what you want to be changed about this behavior if you decide to reopen the ticket.

**Closed by Jelmerro** 2020-06-02 19:06 UTC

**Comment by ipod825** [comment] 2020-06-02 20:09
I appreciate your thoughts on leaving the choice to user. However, I do think there should be an option to toggle this behavior. My major concern is ease of use and consistency with other browser.

I come from other browsers, and in gmail, I am used to use single click to open links in new tab. This becomes a muscle memory such that I don't even think to use middle button. So it's very annoying that every time I click a github link in gmail, I lost my gmail tab. And I guess I will not be only one to face this problem, so I think adding an option to make it behaves like other browser is needed.

**Comment by Jelmerro** [comment] 2020-06-02 21:05
From what I read in the both of your comments, this is only with regards of the mouse clicks, and does not suggest a change to follow mode? If so, I might reconsider adding a setting for this, but I don't think that making these changes to follow mode will be useful.

**Comment by ipod825** [comment] 2020-06-02 21:07
Yes. Only regarding mouse click. I agree that Follow mode should always respect user's choices.
