### ISSUE TITLE
Extremely high CPU usage on certain sites

### ISSUE THREAD

**Issue by Isti115** [Jelmerro/Vieb#267] opened 2021-08-13 13:40 UTC
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Sorry to nag you with issues one after the other, but now that I have started using Vieb as my main browser I have noticed that when a tab with YouTube loaded is in the foreground, the `.electron-wrapped` process starts using 120% CPU on a Ryzen 7 5800X.

**To Reproduce**
The YouTube issue happens pretty consistently, but GitHub has also caused 50%+ usage, in case you need another site to check as well.

**Expected behavior**
Other browsers handle the same sites without any spikes in resources or drops in performance, which I would expect Vieb to do as well.

**Specs**
 - OS: NixOS
 - Version: 13.1.6

**Comment by Jelmerro** [comment] 2021-08-13 13:48
Duplicate of https://github.com/Jelmerro/Vieb/issues/179, not much we can do to solve it without Electron allowing us to add preloads for iframes. Please read that issue for details.

**Closed by Jelmerro** 2021-08-13 13:48 UTC
Labels: bug, duplicate, electron issue
