### ISSUE TITLE
caret characters combinaisons from AZERTY keyboards (âêîôû or even ^z) are detected randomly

### ISSUE THREAD

**Issue by Melandel** [Jelmerro/Vieb#421] opened 2022-09-30 08:00 UTC
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
When I type caret-based characters such as âêîôû or even ^z...
* sometimes I see a, e, i, o, u, z
* sometimes I see a white space
* sometimes I get â ê î ô û ^z as expected (it's really rare)

**To Reproduce**
* type caret followed by a character on azerty keyboard in a text field
* the text field should display something like â ê î ô û or ^z

**Expected behavior**
* sometimes I see a, e, i, o, u, z
* sometimes I see a white space
* sometimes I get â ê î ô û ^z as expected (it's really rare)
* 
**Specs**
 - OS: Windows10
 - Version: 9.2.0

**Note:**
- This behavior was introduced in 9.2.0 because it used to work fine in 9.2.1
- I checked on firefox and other text edition programs on my machine, I get the expected behavior in those environments

**Comment by Jelmerro** [comment] 2022-10-04 14:03
The only change that could have caused this since the latest release would be the Electron/Chromium update. I did find this Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1360070 Though they don't mention Windows explicitly there. Do you perhaps have the same issue if you use Chrome/Chromium 105 or higher? On Windows you can download the latest Chromium here: https://chromium.woolyss.com/download/

I do not have an azerty keyboard, nor can I reproduce this issue with software, hence my request to have you test this in Chromium. Please let me know if you know more.

**Comment by Melandel** [comment] 2022-10-05 18:00
I used your link and downloaded rev [1055271](https://storage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/1055271/), commit [07e2ebf](https://chromium.googlesource.com/chromium/src/+/07e2ebf56abd2f0a9251d6becfe309a88f6065bf), and was able to type in caret characters in, say, the youtube search bar - which I cannot achieve in Vieb 9.2.0

**Comment by Jelmerro** [comment] 2022-10-05 20:01
Interesting, thanks for testing this. So if I understand correctly this is also broken INSIDE the page if you type there, not only in the Vieb url bar?

**Comment by Melandel** [comment] 2022-10-05 20:25
Correct

**Comment by Jelmerro** [comment] 2022-10-05 20:45
In that case I suspect it's a recent Electron issue, are there any other Electron apps you use that have recently updated to 21 that have this problem?

**Comment by Melandel** [comment] 2022-10-05 20:59
Unfortunately, I have no knowledge of any electron app I'd use except for Vieb.

I may try to install nodejs and build Vieb from sources commit by commit in order to identify which commit induced the behavior when I have time

**Comment by Jelmerro** [comment] 2022-10-05 22:21
That would help a lot actually, if you could, because I have no way to reproduce it here.

**Comment by Melandel** [comment] 2022-10-06 17:45
The commit that introduced the unexpected behavior is [add backwards searching and make repeated searches increment ](https://github.com/Jelmerro/Vieb/commit/5dab8e03e4f4468dd0980bc004d618b6fb0db796) (12 days ago)

**Comment by Melandel** [comment] 2022-10-07 21:27
I confirm that commit fixes it, works like a charm!

**Comment by Jelmerro** [comment] 2022-10-07 21:39
Glad to hear, I'll close it and make a release this weekend if all goes well.

**Closed by Jelmerro** 2022-10-07 21:39 UTC
Labels: bug, question
