### ISSUE TITLE
Closing vieb with window manager doesn't work

### ISSUE THREAD

**Issue by gbaranski** [Jelmerro/Vieb#153] opened 2021-04-17 15:33 UTC
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
I'm not able to kill vieb using window manager shortcut.

**To Reproduce**
Install xmonad, add this to your config
```haskell
myKeys conf@(XConfig {XMonad.modMask = modMask}) = Map.fromList $
  [
  -- Close focused window.
  , ((modMask .|. shiftMask, xK_c),
     kill)
  ]
```
Press MOD+Shift+c.

Not sure if that happens only on xmonad, maybe also on other window managers.

**Expected behavior**

MOD+Shift+c should close vieb.

**Specs**
 - OS: Arch Linux
 - Version: 4.4.0

**Comment by Jelmerro** [comment] 2021-04-17 15:38
Duplicate of #65, just add a mapping for `<A-F4>` if you want this.

**Closed by Jelmerro** 2021-04-17 15:38 UTC
Labels: duplicate, question, wontfix

**Comment by gbaranski** [comment] 2021-04-17 16:05
> Duplicate of #65, just add a mapping for `<A-F4>` if you want this.

Every application I've ever used except vieb handles `kill` from WM properly, that would be great to follow this good practicex. I don't think that anyone will use their `kill` shortcut for other purpose, like opening new tab or something.

**Comment by Jelmerro** [comment] 2021-04-17 17:25
If there was any way to differentiate between `<A-F4>` and close requests I would reconsider this, but only offers a 'close' request, which can be user initiated via `<A-F4>` or be any other kind of close such as via kill. With this, Vieb doesn't receive `<A-F4>` as a keybinding, but only as some kind of close request. As such, I decided to make close requests translate to `<A-F4>` and allow the user to choose what they want to do with it, like any other key combination. If there's ever an option added in Electron to differentiate between the keyboard based close and system/commandline close requests I'll probably change it to respect the close requests from kill/cli and leave the `<A-F4>` mapping open for user implementation. But until then, I don't see any change needed in Vieb, and this is absolutely not a bug. If you want to change it, you can do it using any of the example configuration, my listed suggestion or any of the examples from the help page for it.
