### ISSUE TITLE
Adblock does not block YouTube ads

### ISSUE THREAD

**Issue by skunkfox** [Jelmerro/Vieb#346] opened 2022-01-10 19:07 UTC
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Adblock does not currently block YouTube Ads. I have enabled and updated adblock and experimented with loading additional blocklists.

**To Reproduce**
Go to a YouTube video with an ad at the beginning, the ad plays.

**Expected behavior**
The Ad should not play.

**Specs**
 - OS: Manjaro Linux

**Comment by Jelmerro** [comment] 2022-01-10 19:18
I hate to be the bringer of bad news, but this also happens occasionally when using ublock origin with the same blocklists. I believe the problem is that Youtube keeps changing the location of the ads to prevent blocking them with an adblocker, and they sometimes manage to make that work.

Adblock is working fine in Vieb, see sites like [adblock-tester](https://adblock-tester.com/) and such:
![image](https://user-images.githubusercontent.com/1696674/148825490-6dd3813a-af16-4334-bab2-2e1170171467.png)
Either contact the makers of the [adblocker that Vieb](https://github.com/ghostery/adblocker/tree/master/packages/adblocker-electron) is using, or make an issue in the [easylist repo](https://github.com/easylist/easylist/), but it's not an issue with Vieb specifically.

**Comment by skunkfox** [comment] 2022-01-10 23:43
@Jelmerro Thank you for getting back to me so quickly.

I am going to ask you to please re-open this issue. I just performed some comparisons tests between Brave and Vieb regarding this video: https://www.youtube.com/watch?v=dns81NiNzas

In both browsers I am subscribed to EasyList, EasyPrivacy, Fanboy Social and Cookie Monster. However in Vieb I see an advertisement before the YouTube video begins, which I do not see in Brave or Firefox.

I would like to spend some time narrowing down the issue, specifically which adblock rule gets hit or missed when I watch that video on Vieb vs Brave. I would do this tonight but I am currently disassociating on ketamine and even submitting this comment feels like a miracle.

In any case, if you re-open the issue, I will investigate further after work tomorrow.

**Comment by Jelmerro** [comment] 2022-01-11 01:10
I can reopen it, but it's very unlikely that it's  a Vieb issue: there is very little adblocker code in Vieb and the adblocker works for pretty much anything else, so we know it's working. Most of Vieb's adblocker code is just to connect to [this package](https://github.com/ghostery/adblocker/tree/master/packages/adblocker-electron), so I would recommend opening an issue there instead, there have been issues before related to Youtube ads, most of the time it was caused by cosmetic filtering being broken.

**Comment by Jelmerro** [comment] 2022-04-23 22:01
After looking into this once more with some fresh pair of eyes, I have learned that there is another level of blocking involved in most adblockers, including uBlock, which is script overriding. I was only aware with the filters/filter lists, network filtering and cosmetic filtering, but apparently there is also usually a level to override the scripts that inject these ads if they are really nasty (for example youtube) so that they don't get injected in the first place. I was unaware that this even existing when first responding to this ticket, hence my reaction. I will work on a fix for this soon.

**Comment by Jelmerro** [comment] 2022-04-23 22:02
After looking into this once more with some fresh pair of eyes, I have learned that there is another level of blocking involved in most adblockers, including uBlock, which is script overriding. I was only aware with the filters/filter lists, network filtering and cosmetic filtering, but apparently there is also usually a level to override the scripts that inject these ads if they are really nasty (for example youtube) so that they don't get injected in the first place. I was unaware that this even existed when first responding to this ticket, hence my reaction. I will work on a fix for this soon.

**Comment by skunkfox** [comment] 2022-05-01 18:42
> After looking into this once more with some fresh pair of eyes, I have learned that there is another level of blocking involved in most adblockers, including uBlock, which is script overriding. I was only aware with the filters/filter lists, network filtering and cosmetic filtering, but apparently there is also usually a level to override the scripts that inject these ads if they are really nasty (for example youtube) so that they don't get injected in the first place. I was unaware that this even existed when first responding to this ticket, hence my reaction. I will work on a fix for this soon.

Hey, I just wanted to say thank you for taking the time to look into this. I know I mentioned last time that I was going to look into it myself, and I really planned to. But then life happened, and I'm ending up having to move and look for another job.

But I still use Vieb on a daily basis, and I think it's really cool that you are willing to invest the time to support it, even if just on your own.

So thanks again for making a kick-ass browser.

**Comment by Jelmerro** [comment] 2022-05-01 20:50
There is a bit of good news in that this will improve the adblocker, but it's still the case that most youtube updates will bring back ads until this resources file is updated. When I added this to the code it most definitely blocked youtube ads reliably, but now they are back once again, at least until this file is updated. In the end, the only solution to youtube ads is buying youtube premium or not using youtube, either by switching to alternatives or using proxies like invidious, both of which will be better for privacy reasons anyway.

I'm now undecided as what to do with this ticket, on the one hand it did lead to hardening of the adblocker, but on the other hand the issue is not completely solved, as that still seems pretty much impossible to do reliably. I asked a bunch of people I know what their experience is with ublock origin on youtube in firefox/chrome, and it's basically the same mess as the current Vieb situation, it either works or doesn't and it's overall fairly unreliable. Some of them ended up buying youtube premium as a result, accepted that ads won't always be blocked or stopped using the platform as often.

What seems best to do currently, is to add an entry to the FAQ about this, including links like [this one](https://old.reddit.com/r/uBlockOrigin/comments/uekyuk/youtube_ads_are_getting_through/) that explain that it's not really a Vieb issue anymore, especially now that these scripts are also being correctly injected and blocked in the right places, and the ads are still showing up from time to time, just like with ublock.

**Comment by skunkfox** [comment] 2022-05-04 17:58
One thing I wanted to note is that I don't use Firefox much these days. But on Brave, since I started using it a year ago, I have never seen an ad on YouTube.

Maybe they are just updating that resource file on a regular basis and I never watched YouTube at the right time to run into an ad, or maybe there are doing something else. But I thought it was worth noting.

**Comment by Jelmerro** [comment] 2022-05-04 22:27
For Brave, they definitely do have their own resources file for adblocking, actually, it seems there is an entire repo specifically for that purpose: https://github.com/brave/adblock-resources

**Comment by Jelmerro** [comment] 2022-06-08 18:46
Fixed in [the new 8.0.0 release](https://github.com/Jelmerro/Vieb/releases/tag/8.0.0), or at the very least, we now also use script blocking similar to brave and ublock origin. I can now confidently say, that IF using the same blocklists AND resources file, the blocker should work identical.

**Closed by Jelmerro** 2022-06-08 18:46 UTC
Labels: bug

**Comment by veikolippand** [comment] 2022-06-09 06:12
how this should work? do i miss something because out of the box Vieb 8.0.0 does not block youtube (in video) ads. Do i have to add something or change config? What this script blocking mean and how to use it? sorry if i misunderstand this issue.

**Comment by Jelmerro** [comment] 2022-06-09 15:47
I have explained the current situation [in the FAQ](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md#why-do-i-see-ads-on-some-sites-such-as-youtube). If you still see ads, either stop blocking autoplay, as that is known to cause ads to display on youtube, or update the blocklists with specific youtube filters and update them regularly.

**Comment by veikolippand** [comment] 2022-06-09 16:31
sorry didnt know that, my bad.
