### ISSUE TITLE
keeprecentlyclosed does not play well with restoretabs

### ISSUE THREAD

**Issue by kablondino** [Jelmerro/Vieb#96] opened 2020-11-28 16:49 UTC
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [X] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [X] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
`keeprecentlyclosed` setting does not seem to work while `norestoretabs` is set. I wish to have a new, fresh session (no previously opened tabs) every time I open Vieb. However, I would like to be able to restore tabs that were closed during the same session. 

In the documentation under `restoretabs`,
> If this setting is disabled, tabs won't be restored, but will possibly be stored as recently closed tabs so you can reopen them, which is configured with `keeprecentlyclosed`.

These two settings do not seem to work well together, as documented.

**To Reproduce**
I have set the following settings:
```vim
set norestoretabs  " Do not restore tabs from previous session to new one
set keeprecentlyclosed  " Defaulted already to true
nmap <C-T> <action.reopenTab>  " Ctrl + T to open recently closed tab
```
Open some tabs, close them, and attempt to restore them with Ctrl + T

**Specs**
 - OS: [Windows]
 - Version: [3.0.0]

**Comment by Jelmerro** [comment] 2020-11-28 20:26
I think I have found at least one problem in the current implementation that might cause the reopen action to fail. I have fixed this in the latest commit on master. If you could build and check with the latest version (using the build instructions from the readme), that would help a lot.

Can you also further elaborate on what currently happens for you when you execute the reopen action? Because that isn't clear to me.

Finally, I just want to mention that `<C-T>` is actually `ctrl shift t` whereas `<C-t>` means `ctrl t`, but hopefully you know that already. If that's new information for you, could you check if simply pressing `u` also has the restore problem you mention?

**Comment by kablondino** [comment] 2020-11-29 13:00
The last point first: Yes, `<C-T>` is Ctrl + uppercase T. It's the default for Chrome, which is what I wish to have also. `u` behaves in the exact same way.

The exact behavior is somewhat interesting. If I am to open let's say 3 tabs, close two of them, and then press `<C-T>` or `u`, the most-recently closed tab will not reopen. What happens is that the tab that was opened most recently **AND** is still open (but not necessarily active) will be duplicated. This behavior continues to work this way regardless of how many tabs are opened and closed, and which tab is currently active. It's always the most-recently opened tab that is **also** still alive.

I unfortunately am not really able to build from source in a Windows environment, even though I do wish to use it in Windows (and Linux as well). I did end up building it this morning in openSUSE Leap, and the bug was not there. It worked exactly as you and I expect. Perhaps someone could try building it in Windows with the new commits to find if it is fixed.

**Comment by Jelmerro** [comment] 2020-11-29 22:52
Going by your description, I'm fairly certain this is fixed on master. Hopefully I'll release a beta in the next week for you to test on Windows as well.

**Comment by Jelmerro** [comment] 2020-12-06 14:36
Okay, so I decided to just go with a regular release instead, because it's been a while since the last one. There are a lot of other things that I consider stable. I am fairly sure that this issue is solved as well, given that I couldn't reproduce it after the fix. Just make sure that you check this properly, because it won't clean up the old duplicated entries. You can delete those manually from the `tabs` file in the datafolder, or just accept that from now on it should work as expected without duplicating them. Feel free to make a new issue if you have any other problem or suggestion.

**Closed by Jelmerro** 2020-12-06 14:36 UTC
Labels: bug

**Comment by kablondino** [comment] 2020-12-09 01:24
To give an update: I have installed the Windows version just released. From what I can tell, this has fully fixed the issue.
