### ISSUE TITLE
CPU consumption

### ISSUE THREAD

**Issue by errge** [Jelmerro/Vieb#201] opened 2021-05-31 14:43 UTC
**Checklist**
- [x] I searched the `:help` documentation using `/` for helpful information
- [x] I have read the [frequently asked questions](https://github.com/Jelmerro/Vieb/blob/master/FAQ.md)
- [x] I did not find any similar issues in the [issue tracker](https://github.com/Jelmerro/Vieb/issues)

**Describe the bug**
Having a new Vieb window with empty profile and without configs idling on vieb://help consumes ~60% CPU, even when the window is not shown (staying on another workspace in X11).

This might be related to https://github.com/Jelmerro/Vieb/issues/179, but the vieb://help page has no iframes, and also I have no reason to suspect that this is because of my video card (GPU acceleration is correctly enabled according to chrome://gpu).

Different websites consume different amount of CPU, e.g. nilcons.com is only ~5%, but I don't see the reason why can't it be zero when Vieb is not showing at all.

Do you have some links where I could read up on how to profile an electron app?  I tried the profiler in internaldevtools, but the result is 99% idle, which is obviously not true.  I guess either Vieb or electron behind it is looping in some async/setTimeout stuff...

**To Reproduce**

Just download the current Linux AppImage build, and open vieb://help only and look at your CPU usage with top.

**Specs**
 - OS: Debian Linux
 - Version: Tested current git head, and appimage builds back to version 4.0.

**Comment by gebner** [comment] 2021-05-31 15:38
This is probably due to a busy loop checking for iframes, I wanted to clean this up using event handlers, but never got around it.

Here's a quick workaround (that will solve the CPU issue but introduce some delay when following links): https://github.com/gebner/Vieb/commit/182a05271c5a01a1dcd112bc47be40ecb08ca737

**Comment by Jelmerro** [comment] 2021-05-31 17:34
This is (as you hinted at) a duplicate of the linked issue. There is an infinite loop inside Vieb to minimize the risks of iframes and make them register clicks and screensharing requests correctly. I explained them in more detail [here](https://github.com/Jelmerro/Vieb/issues/179#issuecomment-851609483).

Also, the suggestion of @gebner compromises these features for the duration of the interval you set, this includes showing real values for the battery, memory, cpu APIs, as well as allowing full keyboard access, breaking click actions and screensharing.

**Closed by Jelmerro** 2021-05-31 17:34 UTC
Labels: bug, duplicate, upstream issue
